name: React app pipeline
on:
  push:
    branches: [main]

jobs:
  frontend-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      
      - name: setting up node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - name: installing dependencies
        run: npm install
        working-directory: frontend
      
      - name: building application
        run: npm run build
        working-directory: frontend
       
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to S3
        run: aws s3 sync frontend/dist s3://my-react-my-app --delete