name: CI CD
on: push
jobs:
  print-name:
    runs-on: ubuntu-latest
    steps:

      - name: installing node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: installing dependencies
        run: npm install
