name: CI CD
on: 
  push:
    branches: 
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: getting code
        uses: actions/checkout@v3

      - name: setting up node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: installing dependencies
        run: npm install
        working-directory: backend

      - name: running tests
        run: npm test
        working-directory: backend

      - name: building code
        run: npm run build
        working-directory: backend
