name: CI CD
on: push
jobs:
  print-name:
    runs-on: ubuntu-latest
    steps:
      - name: getting code
        uses: actions/checkout@v3
      - name: setting up node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: installing dependencies
        run: npm install
